global:
  tls:
    source: secret
open-webui:
  ollamaUrls:
  - http://suse-private-ai-ollama.suse-private-ai.svc.cluster.local:11434
  persistence:
    enabled: true
    storageClass: ${APPLICATION_STORAGE_CLASS}
  ollama:
    enabled: false
  pipelines:
    enabled: true
    persistence:
      storageClass: ${APPLICATION_STORAGE_CLASS}
  ingress:
    enabled: true
    class: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    host: ${FQDN}
    tls: true
    existingSecret: ${APPLICATION_TLS_SECRET}
  extraEnvVars:
  - name: DEFAULT_MODELS
    value: "gemma:2b"
  - name: DEFAULT_USER_ROLE
    value: "user"
milvus:
  minio:
    persistence:
      size: 50Gi
  pulsar:
    bookkeeper:
      volumes:
        journal:
          size: 20Gi
        ledgers:
          size: 50Gi
  kafka:
    persistence:
      size: 50Gi

